name: biktrix-test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#000000'
    - '#74635b'
    - '#fe9700'
    - '#8f0006'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 0.8276087257545441
purpose: []
